<?xml version="1.0" ?>
<robot name="simple_joint" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find simple_joint_description)/robot/materials.xacro" />
  <xacro:include filename="$(find simple_joint_description)/robot/properties.xacro" />
  <xacro:include filename="$(find simple_joint_description)/robot/macros.xacro" />
  <xacro:include filename="$(find simple_joint_description)/robot/wheels.xacro" />
  <xacro:include filename="$(find simple_joint_description)/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find simple_joint_description)/robot/simple_joint_body.xacro" />
  <xacro:include filename="$(find simple_joint_description)/robot/simple_joint.gazebo" />

  <!--
  <xacro:include filename="$(find simple_joint_description)/robot/simple_joint_propeller.xacro" />
  -->
  
  <xacro:simple_joint_body parent_name="${base_name}"/>

  
  <xacro:link_wheel name="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" parent="${base_name}" child="right_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" />

  <xacro:link_wheel name="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" parent="${base_name}" child="left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" />


  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  <xacro:caster_wheel parent="chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" legth="${dummy_length}"/>
  

</robot>
